source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


# ignore all warnings from all pods
inhibit_all_warnings!

def pods()
    pod 'Socket.IO-Client-Swift', '~> 8.1.2'
end

def testpods()
    pod 'OCMockito', '~> 4.0'
    pod 'OCMock', '~> 3.1'
    pod 'DCKeyValueObjectMapping'
    pod 'Socket.IO-Client-Swift', '~> 8.1.2'

end


target 'BringgTracking-iOS' do
    pods()
end

target 'BringgTracking-iOSTests' do
    testpods()
end

target 'BringgTracking-OSX' do
    pods()
end

target 'BringgTracking-OSXTests' do
    testpods()
end

target 'BringgTracking-TVOS' do
    pods()
end

target 'BringgTracking-TVOSTests' do
    testpods()
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
