source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


# ignore all warnings from all pods
inhibit_all_warnings!

target 'BringgTracking-iOS' do
    use_frameworks!
    pod 'Socket.IO-Client-Swift', '~> 15.1.0'
end

target 'BringgTracking-iOSTests' do
    use_frameworks!
    pod 'OCMockito', '~> 4.0'
    pod 'OCMock', '~> 3.1'
    pod 'Socket.IO-Client-Swift', '~> 15.1.0'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
