version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    macos:
      xcode: 10.2.0
    steps:
      - checkout
      - run:
            name: Configure git
            command: |
              git config credential.helper 'cache --timeout=120'
              git config user.email "bringg-ios-developers@bringg.com"
              git config user.name "CircleCI"
      - run:
            name: Bundler - Install Dependencies
            command: cd BringgTrackingFramework && bundler install --path .bundle.

      - run:
            name: Cocoapods - Install Dependencies
            command: |
              curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
              cd BringgTrackingFramework && bundle exec pod install

      - run:
            name: Update fastlane
            command: bundle update fastlane
      - run:
            name: Fastlane - Run Unit Tests
            command: cd BringgTrackingFramework && bundle exec fastlane test
      - store_test_results:
            path: BringgTrackingFramework/fastlane/test_output
      - store_artifacts:
            path: BringgTrackingFramework/fastlane/test_output
      - codecov/upload:
          file: BringgTrackingFramework/fastlane/test_output/report.junit
