# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
      update_fastlane
      ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Run unit tests"
  lane :test do
    scan
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
